name: dotnet package

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x
      - name: Install dependencies
        run: dotnet restore GeneratorCalculation.sln
      - name: Build
        run: dotnet build --no-restore GeneratorCalculation.sln
      - name: Test
        run: dotnet test --no-restore --verbosity normal GeneratorCalculation.sln
